/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mortbay_setuid_SetUmask */

#ifndef _Included_org_mortbay_setuid_SetUmask
#define _Included_org_mortbay_setuid_SetUmask
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mortbay_setuid_SetUmask_OK
#define org_mortbay_setuid_SetUmask_OK 0L
#undef org_mortbay_setuid_SetUmask_ERROR
#define org_mortbay_setuid_SetUmask_ERROR -1L
/*
 * Class:     org_mortbay_setuid_SetUmask
 * Method:    setumask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mortbay_setuid_SetUmask_setumask
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
