/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mortbay_setuid_SetUID */

#ifndef _Included_org_mortbay_setuid_SetUID
#define _Included_org_mortbay_setuid_SetUID
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mortbay_setuid_SetUID_OK
#define org_mortbay_setuid_SetUID_OK 0L
#undef org_mortbay_setuid_SetUID_ERROR
#define org_mortbay_setuid_SetUID_ERROR -1L
/*
 * Class:     org_mortbay_setuid_SetUID
 * Method:    setuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mortbay_setuid_SetUID_setuid
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
